all:
	@javac trab2.java

clean:
	@rm -f *.class Items/*.class
	@find -name "*~" | xargs rm -rf

run:
	@java trab2

# sera usado somente para testar os metodos das classes atraves de mainTest.java
test:
	@javac mainTest.java

runT:
	@java mainTest

